### PR TITLE
Allow method braces to open on line after method name

### PR DESCRIPTION
**Pull request by paulbruneau**

### CODE REVIEW

**Comment by mattbischoff** [comment]
Borrowing from the [PEP 20](https://www.python.org/dev/peps/pep-0020/), I’d argue that “There should be one-- and preferably only one --obvious way to do it.”

**Comment by paulbruneau** [comment]
That sound fine, but I know that people won't go for the way I like to do it.

**Comment by mattbischoff** [comment]
Sure, but the point here is that `{`’s should always follow the same rules. You shouldn’t have to think, is this a method or is this an `if` statement.

**Comment by paulbruneau** [comment]
I wouldn't have created this pull request (that admittedly has a nearly zero chance of success) except that people are starting to get in my grill about the tiny differences my code has with the style guide.

**Comment by paulbruneau** [comment]
I like a space after my method names. Putting the brace down gives me one. Also I can triple click the method name to copy it over to an .h file if I need to without having to then delete the brace and the space. Which admittedly sounds very insignificant but I find it annoying.

**Comment by bcapps** [comment]
Why don't you like a space for other statements?

**Comment by paulbruneau** [comment]
When I'm looking at code, I like the method names to stand out more so it's easier for me to see where the methods start and end. That isn't necessary of course for ifs and such.

**Comment by paulbruneau** [comment]
Interesting, I just happened to notice that Luke Redpath agrees with the way I do it:

````Method braces always appear on a line of their own. Other braces (if/else/switch/while etc.) open on the same line as the statement but close on a new line.````

**Comment by loganmoseley** [comment]
What happens, according to the current canon, when a method signature is too long to comfortably fit on one line? People will often put each parameter on a new line. If that's allowed, does the brace sit at the end of the line with the last parameter or on a new-line? The style guide does not specifically address it, so I'm guessing the brace comes immediately after the last parameter. That's the most difficult of method sigs to read, in my opinion.

Alamo Fire's style is same-line brace for single-line method signatures, new-line brace for multi-line method signatures. [Example here.](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFHTTPRequestOperationManager.m#L119)

**Comment by paulbruneau** [comment]
Interesting, but pretty nasty without the colon alignment I think!

**Comment by cdzombak** [comment]
I'm ambivalent on this in general, honestly; I think ObjC method declarations are doomed to be ugly no matter what we do.

I will note that given a multiline method declaration, I prefer the opening brace on a newline to provide visual distinction. But I don't feel strongly about it, either.

**Comment by elsh** [comment]
I also prefer the opening brace on a new line for both single- and multi-line method decls because it gives a clear visual cue that it's the start of the method implementation and adds space between the method name and the body which makes things more readable.

**Comment by dzlobin** [comment]
I also prefer { on a new line for both methods and if/switch. While I enjoy the look of short methods with { on the same line, overall I find it creates much more readable code.

**Comment by Veronique** [comment]
I used to also prefer { on a new line until I started using the Xcode Code Folding options which have become my prefered way to work especially when working in a large class.
@paulbruneau Try Editor > Code Folding > Focus Follows Section and see if you like it.

**Comment by Twigz** [comment]
Closed in favor of #118

We believe the use of braces is important for consistency across methods and other statements. While Xcode autocomplete continues to complete these other statements with braces on the same line, we will continue to mandate braces be written on the same line. That being said, we also appreciate the need for visual separation between the name of a method and its body. #118 adds an explicit statement to allow such behavior.

**Pull request closed without merging**
